import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SimpleThreeColumns from '@/components/OurServices/OurServices'
import Contact from '@/components/Contact/Contact'
import Details from '@/components/MoreServices/Details'
import Card from '@/components/AboutMe/Card'
import Header from '@/components/Header/Header'
import { Fade } from 'react-awesome-reveal'


export default function Home() {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fade direction="down" cascade onVisibilityChange={(inView) => console.log(inView)}>
        <Header />
      </Fade>
      <Fade direction="down" cascade>
        <SimpleThreeColumns />
      </Fade>
      <Fade direction="down" cascade>
        <Details />
      </Fade>
      <Fade direction="down" cascade>
        <Card />
      </Fade>
      <Fade direction="down" cascade>
        <Contact />
      </Fade>
    </>
  )
}
